name: 'Pull Request Labeler'
description: 'Label pull requests by files altered'
author: 'GitHub'
inputs: 
  access-token:
    description: 'Access token'
  repo-token:
    description: 'The GITHUB_TOKEN secret'
runs:
  using: 'node12'
  main: 'lib/main.js'
